version: '3.8'

services:
  whisper-subtitles:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime-whisper-subtitles
    
    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Environment variables
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - PULSE_COOKIE_DATA=/tmp/pulse-cookie
    
    # Audio device access
    devices:
      - /dev/snd:/dev/snd
    
    # Volume mounts
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ~/.cache/pip:/root/.cache/pip
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # Port mappings
    ports:
      - "8000:8000"  # Web Interface
      - "8888:8888"  # Debug/Development
    
    # Working directory
    working_dir: /app
    
    # Startup command
    command: >
      sh -c "
        echo 'Starting Real-time Whisper Subtitles System...' &&
        python -c 'import torch; print(f\"CUDA available: {torch.cuda.is_available()}\"); print(f\"GPU count: {torch.cuda.device_count()}\"); print(f\"GPU name: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"No GPU\"}\")' &&
        python src/web_interface.py
      "
    
    # Restart policy
    restart: unless-stopped
    
    # Network
    networks:
      - whisper-network
    
    # Privileges for audio access
    privileged: true

# Network configuration
networks:
  whisper-network:
    driver: bridge